export const adminCopy = {
  kicker: 'Internal',
  title: 'Admin',
  lede: 'Manage staff sign-in accounts and the buyer product catalogue. Review queues stay at /staff. HTTP Basic against app_users — not SSO.',
  signInHint:
    'Use an administrator work email. Seeded local login: admin@sarv.local with the staff password set on this server.',
  forbidden:
    'This panel is for administrators only. Supplier and buyer queues are on the staff review screen.',
  openStaff: 'Open staff review',
  accountsTitle: 'Staff accounts',
  accountsLede:
    'Create and update staff IDs (work email, roles, status). Accounts are deactivated rather than deleted so review history stays intact.',
  createTitle: 'New staff account',
  editTitle: 'Edit staff account',
  email: 'Work email',
  displayName: 'Display name',
  password: 'Password',
  passwordCreateHint: 'At least 8 characters. The person signs in with this email and password.',
  passwordEditHint: 'Leave blank to keep the current password.',
  roles: 'Roles',
  status: 'Status',
  save: 'Save account',
  create: 'Create account',
  cancel: 'Cancel',
  edit: 'Edit',
  deactivate: 'Deactivate',
  deactivateConfirm: (email: string) =>
    `Deactivate ${email}? They will not be able to sign in. Review history is kept.`,
  empty: 'No staff accounts yet.',
  selfNote: 'This is your signed-in account.',
  prototypeNote:
    'Passwords are stored as hashes. Seeded poc-* accounts may be rotated on server start when EXHIBITION_STAFF_BOOTSTRAP_PASSWORD is set. Accounts created here keep the password you set.',
  tabStaff: 'Staff IDs',
  tabCatalogue: 'Buyer catalogue',
  catalogueTitle: 'Trading and offline suppliers',
  catalogueLede:
    'Buyer “I want to buy” can pick Sarv finished goods plus products you list here. Pharma-erp sync stays on /staff. Tag a product to make it searchable for buyers (names only — no item codes).',
  offlineTitle: 'Add offline supplier',
  company: 'Company name',
  contact: 'Contact name',
  phone: 'Phone',
  website: 'Website',
  notes: 'Internal notes',
  addSupplier: 'Add supplier',
  portalTitle: 'Portal-registered suppliers',
  portalLede:
    'Submitted “I want to sell” inquiries. Add one to the trading directory, then tag products for buyers. This does not Add to production or create an enterprise vendor.',
  addFromPortal: 'Add to trading directory',
  noPortal: 'No unlinked submitted suppliers.',
  products: 'Products',
  productName: 'Product name',
  listForBuyers: 'List for buyers',
  addProduct: 'Add product',
  noProducts: 'No products yet.',
  suggested: 'From their submitted product types',
  addSuggested: 'Add',
  listed: 'Listed',
  notListed: 'Not listed',
  noSuppliers: 'No trading suppliers yet.',
  sourceOffline: 'Offline',
  sourcePortal: 'Portal',
} as const
