-- Exhibition Portal schema — historical PostgreSQL singleton.
-- Derived from DATABASE-DESIGN.md.
-- IDs are generated by the application; no PostgreSQL UUID extension is required.
-- This file is intentionally a single, ORM-neutral DDL baseline.
--
-- Do not load this file. The applied store is MySQL 8 via
-- backend/src/main/resources/db/migration/ (Flyway V1–V5). Scan-first mismatches
-- (nullable inquiries.route, nullable inquiry_parties.company_name_submitted)
-- are in those migrations.
-- See specs/BUILD-PLAN.md §3.

BEGIN;

CREATE SCHEMA IF NOT EXISTS exhibition_portal;
SET search_path TO exhibition_portal, public;

CREATE OR REPLACE FUNCTION exhibition_portal.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- ============================================================================
-- Internal identity and authorization
-- ============================================================================

CREATE TABLE app_users (
    id uuid PRIMARY KEY,
    external_subject text NOT NULL UNIQUE,
    email_normalized text NOT NULL UNIQUE,
    display_name text NOT NULL,
    status text NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    id uuid PRIMARY KEY,
    code varchar(64) NOT NULL UNIQUE,
    name text NOT NULL,
    description text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE RESTRICT,
    role_id uuid NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    assigned_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by_user_id uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    PRIMARY KEY (user_id, role_id)
);

-- ============================================================================
-- Exhibition entry and QR attribution
-- ============================================================================

CREATE TABLE exhibitions (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    timezone_name text NOT NULL,
    venue_name text,
    geofence_latitude numeric(9, 6),
    geofence_longitude numeric(9, 6),
    geofence_radius_m integer,
    status text NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT', 'ACTIVE', 'CLOSED', 'ARCHIVED')),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT exhibitions_time_range_valid CHECK (ends_at > starts_at),
    CONSTRAINT exhibitions_geofence_complete CHECK (
        (geofence_latitude IS NULL AND geofence_longitude IS NULL AND geofence_radius_m IS NULL)
        OR (
            geofence_latitude IS NOT NULL
            AND geofence_longitude IS NOT NULL
            AND geofence_radius_m IS NOT NULL
            AND geofence_radius_m > 0
        )
    )
);

CREATE TABLE qr_campaigns (
    id uuid PRIMARY KEY,
    exhibition_id uuid REFERENCES exhibitions(id) ON DELETE RESTRICT,
    code text NOT NULL UNIQUE,
    label text NOT NULL,
    landing_route text NOT NULL DEFAULT 'CHOICE'
        CHECK (landing_route IN ('CHOICE', 'SUPPLIER', 'PURCHASE')),
    active_from timestamptz,
    active_until timestamptz,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT qr_campaigns_active_range_valid CHECK (
        active_until IS NULL OR active_from IS NULL OR active_until > active_from
    )
);

-- ============================================================================
-- Admin-managed business taxonomy
-- ============================================================================

CREATE TABLE departments (
    id uuid PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name text NOT NULL,
    description text,
    display_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_types (
    id uuid PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name text NOT NULL,
    description text,
    display_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE department_product_types (
    department_id uuid NOT NULL REFERENCES departments(id) ON DELETE RESTRICT,
    product_type_id uuid NOT NULL REFERENCES product_types(id) ON DELETE RESTRICT,
    display_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (department_id, product_type_id)
);

CREATE TABLE pharmacopoeial_standards (
    id uuid PRIMARY KEY,
    code varchar(16) NOT NULL UNIQUE,
    name text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id uuid PRIMARY KEY,
    product_type_id uuid NOT NULL REFERENCES product_types(id) ON DELETE RESTRICT,
    code varchar(80) NOT NULL UNIQUE,
    name text NOT NULL,
    cas_number varchar(32),
    product_family text NOT NULL
        CHECK (product_family IN (
            'API',
            'INTERMEDIATE',
            'PHYTOCHEMICAL',
            'HERBAL_EXTRACT',
            'ONCOLOGY',
            'SPECIALTY_CHEMICAL'
        )),
    description text,
    display_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_standards (
    product_id uuid NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    standard_id uuid NOT NULL REFERENCES pharmacopoeial_standards(id) ON DELETE RESTRICT,
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (product_id, standard_id)
);

-- ============================================================================
-- Canonical identity candidates and immutable submission snapshots
-- ============================================================================

CREATE TABLE organizations (
    id uuid PRIMARY KEY,
    legal_name text NOT NULL,
    normalized_name text NOT NULL,
    website_url text,
    tax_identifier_encrypted bytea,
    match_state text NOT NULL DEFAULT 'UNVERIFIED'
        CHECK (match_state IN ('UNVERIFIED', 'CONFIRMED', 'MERGED')),
    merged_into_organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT organizations_merge_state_valid CHECK (
        (match_state = 'MERGED' AND merged_into_organization_id IS NOT NULL)
        OR (match_state <> 'MERGED' AND merged_into_organization_id IS NULL)
    ),
    CONSTRAINT organizations_no_self_merge CHECK (
        merged_into_organization_id IS NULL OR merged_into_organization_id <> id
    )
);

CREATE TABLE contacts (
    id uuid PRIMARY KEY,
    organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,
    first_name text,
    last_name text,
    email_normalized text,
    phone_e164 varchar(20),
    job_title text,
    match_state text NOT NULL DEFAULT 'UNVERIFIED'
        CHECK (match_state IN ('UNVERIFIED', 'CONFIRMED', 'MERGED')),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contacts_name_present CHECK (
        first_name IS NOT NULL OR last_name IS NOT NULL
    )
);

-- ============================================================================
-- Canonical inquiry and route extensions
-- ============================================================================

CREATE TABLE inquiries (
    id uuid PRIMARY KEY,
    reference_code text NOT NULL UNIQUE,
    route text NOT NULL CHECK (route IN ('SUPPLIER', 'PURCHASE')),
    entry_channel text NOT NULL
        CHECK (entry_channel IN ('EXHIBITION_QR', 'WEBSITE', 'DIRECT')),
    qr_campaign_id uuid REFERENCES qr_campaigns(id) ON DELETE RESTRICT,
    exhibition_id uuid REFERENCES exhibitions(id) ON DELETE RESTRICT,
    lifecycle_state text NOT NULL DEFAULT 'DRAFT'
        CHECK (lifecycle_state IN (
            'DRAFT',
            'SUBMITTED',
            'CANCELLED',
            'ARCHIVED',
            'RETENTION_PURGED'
        )),
    submitted_at timestamptz,
    submitted_language_code varchar(10),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inquiries_submission_state_valid CHECK (
        (lifecycle_state = 'SUBMITTED' AND submitted_at IS NOT NULL)
        OR lifecycle_state <> 'SUBMITTED'
    ),
    CONSTRAINT inquiries_qr_channel_valid CHECK (
        entry_channel <> 'EXHIBITION_QR' OR qr_campaign_id IS NOT NULL
    )
);

CREATE TABLE supplier_inquiries (
    inquiry_id uuid PRIMARY KEY REFERENCES inquiries(id) ON DELETE RESTRICT,
    review_state text NOT NULL DEFAULT 'DRAFT'
        CHECK (review_state IN (
            'DRAFT',
            'SUBMITTED',
            'UNDER_REVIEW',
            'NEEDS_INFORMATION',
            'APPROVED',
            'REJECTED'
        )),
    assigned_to_user_id uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    production_state text NOT NULL DEFAULT 'NOT_REQUESTED'
        CHECK (production_state IN (
            'NOT_REQUESTED',
            'QUEUED',
            'IN_PROGRESS',
            'SUCCEEDED',
            'FAILED'
        )),
    approved_at timestamptz,
    approved_by_user_id uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT supplier_inquiries_approval_valid CHECK (
        (review_state = 'APPROVED' AND approved_at IS NOT NULL AND approved_by_user_id IS NOT NULL)
        OR (
            review_state <> 'APPROVED'
            AND approved_at IS NULL
            AND approved_by_user_id IS NULL
        )
    )
);

CREATE TABLE purchase_inquiries (
    inquiry_id uuid PRIMARY KEY REFERENCES inquiries(id) ON DELETE RESTRICT,
    lead_state text NOT NULL DEFAULT 'DRAFT'
        CHECK (lead_state IN (
            'DRAFT',
            'SUBMITTED',
            'QUEUED',
            'DISPATCHED',
            'DELIVERY_FAILED',
            'IN_PROGRESS',
            'CLOSED',
            'DISQUALIFIED'
        )),
    assigned_to_user_id uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    first_dispatched_at timestamptz,
    marketing_notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inquiry_parties (
    id uuid PRIMARY KEY,
    inquiry_id uuid NOT NULL REFERENCES inquiries(id) ON DELETE RESTRICT,
    role text NOT NULL CHECK (role IN ('SUPPLIER_CONTACT', 'BUYER_CONTACT')),
    organization_id uuid REFERENCES organizations(id) ON DELETE SET NULL,
    contact_id uuid REFERENCES contacts(id) ON DELETE SET NULL,
    company_name_submitted text NOT NULL,
    person_name_submitted text NOT NULL,
    email_submitted text NOT NULL,
    email_normalized text NOT NULL,
    phone_submitted text,
    phone_e164 varchar(20),
    job_title_submitted text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (inquiry_id, role)
);

CREATE TABLE party_addresses (
    id uuid PRIMARY KEY,
    inquiry_party_id uuid NOT NULL REFERENCES inquiry_parties(id) ON DELETE RESTRICT,
    address_kind text NOT NULL CHECK (address_kind IN ('BUSINESS', 'POSTAL', 'OTHER')),
    line_1 text,
    line_2 text,
    city text,
    state_region text,
    postal_code text,
    country_code char(2),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT party_addresses_country_code_valid CHECK (
        country_code IS NULL OR country_code ~ '^[A-Z]{2}$'
    )
);

-- ============================================================================
-- Supplier selection and catalogue workflow
-- ============================================================================

CREATE TABLE supplier_inquiry_departments (
    inquiry_id uuid NOT NULL REFERENCES supplier_inquiries(inquiry_id) ON DELETE RESTRICT,
    department_id uuid NOT NULL REFERENCES departments(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (inquiry_id, department_id)
);

CREATE TABLE supplier_inquiry_product_types (
    inquiry_id uuid NOT NULL,
    department_id uuid NOT NULL,
    product_type_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (inquiry_id, department_id, product_type_id),
    CONSTRAINT supplier_product_type_selected_department_fk
        FOREIGN KEY (inquiry_id, department_id)
        REFERENCES supplier_inquiry_departments(inquiry_id, department_id)
        ON DELETE RESTRICT,
    CONSTRAINT supplier_product_type_department_mapping_fk
        FOREIGN KEY (department_id, product_type_id)
        REFERENCES department_product_types(department_id, product_type_id)
        ON DELETE RESTRICT
);

CREATE TABLE catalogue_bundles (
    id uuid PRIMARY KEY,
    supplier_inquiry_id uuid NOT NULL REFERENCES supplier_inquiries(inquiry_id) ON DELETE RESTRICT,
    submission_format text NOT NULL CHECK (submission_format IN ('PDF', 'IMAGES', 'MIXED')),
    processing_state text NOT NULL DEFAULT 'PENDING_SCAN'
        CHECK (processing_state IN (
            'PENDING_SCAN',
            'PROCESSING',
            'READY',
            'FAILED',
            'REJECTED'
        )),
    failure_reason text,
    submitted_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT catalogue_bundles_completed_state_valid CHECK (
        (processing_state IN ('READY', 'FAILED', 'REJECTED') AND completed_at IS NOT NULL)
        OR processing_state NOT IN ('READY', 'FAILED', 'REJECTED')
    )
);

-- ============================================================================
-- Purchase requirement workflow
-- ============================================================================

CREATE TABLE purchase_line_items (
    id uuid PRIMARY KEY,
    purchase_inquiry_id uuid NOT NULL REFERENCES purchase_inquiries(inquiry_id) ON DELETE RESTRICT,
    product_id uuid REFERENCES products(id) ON DELETE RESTRICT,
    requirement_text text,
    quantity_text text,
    display_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT purchase_line_items_requirement_present CHECK (
        product_id IS NOT NULL OR requirement_text IS NOT NULL
    )
);

CREATE TABLE purchase_line_item_standards (
    purchase_line_item_id uuid NOT NULL REFERENCES purchase_line_items(id) ON DELETE RESTRICT,
    standard_id uuid NOT NULL REFERENCES pharmacopoeial_standards(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (purchase_line_item_id, standard_id)
);

-- ============================================================================
-- Secure object-storage asset registry
-- ============================================================================

CREATE TABLE file_assets (
    id uuid PRIMARY KEY,
    inquiry_id uuid NOT NULL REFERENCES inquiries(id) ON DELETE RESTRICT,
    catalogue_bundle_id uuid REFERENCES catalogue_bundles(id) ON DELETE RESTRICT,
    source_asset_id uuid REFERENCES file_assets(id) ON DELETE RESTRICT,
    purpose text NOT NULL CHECK (purpose IN (
        'CATALOGUE_ORIGINAL',
        'CATALOGUE_DERIVED_PDF',
        'BUSINESS_CARD',
        'VOICE_INPUT',
        'EXCEL_EXPORT'
    )),
    original_filename text NOT NULL,
    media_type text NOT NULL,
    byte_size bigint NOT NULL CHECK (byte_size > 0),
    sha256_digest char(64) NOT NULL CHECK (sha256_digest ~ '^[0-9a-f]{64}$'),
    storage_key text NOT NULL UNIQUE,
    security_scan_state text NOT NULL DEFAULT 'PENDING'
        CHECK (security_scan_state IN ('PENDING', 'CLEAN', 'REJECTED', 'FAILED')),
    processing_state text NOT NULL DEFAULT 'UPLOADED'
        CHECK (processing_state IN ('UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'PURGED')),
    retention_until timestamptz NOT NULL,
    purged_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT file_assets_catalogue_bundle_required CHECK (
        purpose NOT IN ('CATALOGUE_ORIGINAL', 'CATALOGUE_DERIVED_PDF')
        OR catalogue_bundle_id IS NOT NULL
    ),
    CONSTRAINT file_assets_derived_source_required CHECK (
        purpose <> 'CATALOGUE_DERIVED_PDF' OR source_asset_id IS NOT NULL
    )
);

-- ============================================================================
-- Consent, voluntary location evidence, and AI assistance
-- ============================================================================

CREATE TABLE consent_records (
    id uuid PRIMARY KEY,
    inquiry_id uuid NOT NULL REFERENCES inquiries(id) ON DELETE RESTRICT,
    purpose text NOT NULL CHECK (purpose IN (
        'LOCATION_EVIDENCE',
        'BUSINESS_CARD_EXTRACTION',
        'VOICE_PROCESSING'
    )),
    policy_version text NOT NULL,
    decision text NOT NULL CHECK (decision IN ('GRANTED', 'DECLINED', 'REVOKED')),
    decided_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT consent_records_revocation_valid CHECK (
        (decision = 'REVOKED' AND revoked_at IS NOT NULL)
        OR (decision <> 'REVOKED' AND revoked_at IS NULL)
    )
);

CREATE TABLE location_evidence (
    id uuid PRIMARY KEY,
    inquiry_id uuid NOT NULL REFERENCES inquiries(id) ON DELETE RESTRICT,
    consent_id uuid NOT NULL REFERENCES consent_records(id) ON DELETE RESTRICT,
    exhibition_id uuid REFERENCES exhibitions(id) ON DELETE RESTRICT,
    source text NOT NULL CHECK (source IN (
        'BROWSER_GPS',
        'NETWORK_DERIVED',
        'QR_EVENT',
        'DECLINED',
        'UNAVAILABLE'
    )),
    captured_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    accuracy_m integer CHECK (accuracy_m IS NULL OR accuracy_m >= 0),
    is_on_site boolean,
    distance_to_event_m integer CHECK (distance_to_event_m IS NULL OR distance_to_event_m >= 0),
    latitude_encrypted bytea,
    longitude_encrypted bytea,
    encryption_key_reference text,
    precise_data_purge_at timestamptz NOT NULL,
    purged_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT location_evidence_precise_value_pair CHECK (
        (latitude_encrypted IS NULL AND longitude_encrypted IS NULL)
        OR (latitude_encrypted IS NOT NULL AND longitude_encrypted IS NOT NULL)
    ),
    CONSTRAINT location_evidence_key_reference_valid CHECK (
        (latitude_encrypted IS NULL AND encryption_key_reference IS NULL)
        OR (latitude_encrypted IS NOT NULL AND encryption_key_reference IS NOT NULL)
    )
);

CREATE TABLE ai_assistance_sessions (
    id uuid PRIMARY KEY,
    inquiry_id uuid NOT NULL REFERENCES inquiries(id) ON DELETE RESTRICT,
    consent_id uuid NOT NULL REFERENCES consent_records(id) ON DELETE RESTRICT,
    feature text NOT NULL CHECK (feature IN ('VOICE_INPUT', 'BUSINESS_CARD_SCAN')),
    language_code varchar(10),
    state text NOT NULL DEFAULT 'STARTED'
        CHECK (state IN ('STARTED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    provider_request_reference text,
    started_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_sessions_completed_state_valid CHECK (
        (state IN ('COMPLETED', 'FAILED', 'CANCELLED') AND completed_at IS NOT NULL)
        OR state NOT IN ('COMPLETED', 'FAILED', 'CANCELLED')
    )
);

CREATE TABLE ai_extractions (
    id uuid PRIMARY KEY,
    session_id uuid NOT NULL REFERENCES ai_assistance_sessions(id) ON DELETE RESTRICT,
    input_asset_id uuid REFERENCES file_assets(id) ON DELETE RESTRICT,
    state text NOT NULL DEFAULT 'PENDING'
        CHECK (state IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    provider_model_reference text,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_extractions_completed_state_valid CHECK (
        (state IN ('COMPLETED', 'FAILED') AND completed_at IS NOT NULL)
        OR state NOT IN ('COMPLETED', 'FAILED')
    )
);

CREATE TABLE ai_extracted_fields (
    id uuid PRIMARY KEY,
    extraction_id uuid NOT NULL REFERENCES ai_extractions(id) ON DELETE RESTRICT,
    field_key varchar(100) NOT NULL,
    proposed_value_text text,
    confidence_score numeric(4, 3)
        CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)),
    review_state text NOT NULL DEFAULT 'PENDING'
        CHECK (review_state IN ('PENDING', 'ACCEPTED', 'CORRECTED', 'REJECTED')),
    reviewed_by_user_id uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    reviewed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (extraction_id, field_key),
    CONSTRAINT ai_extracted_fields_review_valid CHECK (
        (review_state = 'PENDING' AND reviewed_by_user_id IS NULL AND reviewed_at IS NULL)
        OR (review_state <> 'PENDING' AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL)
    )
);

-- ============================================================================
-- Review, workflow history, external delivery, exports, and audit history
-- ============================================================================

CREATE TABLE review_cases (
    id uuid PRIMARY KEY,
    supplier_inquiry_id uuid NOT NULL REFERENCES supplier_inquiries(inquiry_id) ON DELETE RESTRICT,
    state text NOT NULL DEFAULT 'OPEN'
        CHECK (state IN ('OPEN', 'IN_REVIEW', 'WAITING_FOR_INFO', 'CLOSED')),
    assigned_to_user_id uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    opened_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT review_cases_closed_state_valid CHECK (
        (state = 'CLOSED' AND closed_at IS NOT NULL)
        OR (state <> 'CLOSED' AND closed_at IS NULL)
    )
);

CREATE TABLE review_decisions (
    id uuid PRIMARY KEY,
    review_case_id uuid NOT NULL REFERENCES review_cases(id) ON DELETE RESTRICT,
    decision text NOT NULL CHECK (decision IN (
        'REQUEST_INFORMATION',
        'APPROVE',
        'REJECT'
    )),
    reason_code text,
    notes text,
    decided_by_user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE RESTRICT,
    decided_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE deduplication_matches (
    id uuid PRIMARY KEY,
    inquiry_id uuid NOT NULL REFERENCES inquiries(id) ON DELETE RESTRICT,
    candidate_organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,
    candidate_contact_id uuid REFERENCES contacts(id) ON DELETE RESTRICT,
    score numeric(5, 4) NOT NULL CHECK (score >= 0 AND score <= 1),
    state text NOT NULL DEFAULT 'PENDING'
        CHECK (state IN ('PENDING', 'CONFIRMED_DUPLICATE', 'NOT_A_DUPLICATE', 'MERGED')),
    resolved_by_user_id uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT deduplication_matches_candidate_present CHECK (
        candidate_organization_id IS NOT NULL OR candidate_contact_id IS NOT NULL
    ),
    CONSTRAINT deduplication_matches_resolution_valid CHECK (
        (state = 'PENDING' AND resolved_by_user_id IS NULL AND resolved_at IS NULL)
        OR (state <> 'PENDING' AND resolved_by_user_id IS NOT NULL AND resolved_at IS NOT NULL)
    )
);

CREATE TABLE workflow_events (
    id uuid PRIMARY KEY,
    inquiry_id uuid NOT NULL REFERENCES inquiries(id) ON DELETE RESTRICT,
    workflow text NOT NULL CHECK (workflow IN (
        'INQUIRY',
        'SUPPLIER_REVIEW',
        'VENDOR_DELIVERY',
        'PURCHASE_LEAD',
        'CRM_DELIVERY'
    )),
    from_state text,
    to_state text NOT NULL,
    actor_kind text NOT NULL CHECK (actor_kind IN ('VISITOR', 'USER', 'SYSTEM', 'INTEGRATION')),
    actor_user_id uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    reason_code text,
    notes text,
    occurred_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT workflow_events_actor_valid CHECK (
        (actor_kind = 'USER' AND actor_user_id IS NOT NULL)
        OR (actor_kind <> 'USER' AND actor_user_id IS NULL)
    )
);

CREATE TABLE integration_deliveries (
    id uuid PRIMARY KEY,
    inquiry_id uuid NOT NULL REFERENCES inquiries(id) ON DELETE RESTRICT,
    delivery_kind text NOT NULL CHECK (delivery_kind IN ('VENDOR_UPSERT', 'MARKETING_LEAD')),
    destination text NOT NULL,
    idempotency_key text NOT NULL UNIQUE,
    state text NOT NULL DEFAULT 'PENDING'
        CHECK (state IN (
            'PENDING',
            'IN_PROGRESS',
            'SUCCEEDED',
            'RETRY_SCHEDULED',
            'FAILED',
            'CANCELLED'
        )),
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at timestamptz,
    last_attempt_at timestamptz,
    external_reference text,
    last_error_code text,
    last_error_message text,
    request_payload_version varchar(32) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE export_jobs (
    id uuid PRIMARY KEY,
    requested_by_user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE RESTRICT,
    scope text NOT NULL CHECK (scope IN ('PURCHASE_LEADS', 'SUPPLIER_INQUIRIES')),
    filter_summary jsonb NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(filter_summary) = 'object'),
    state text NOT NULL DEFAULT 'QUEUED'
        CHECK (state IN ('QUEUED', 'GENERATING', 'READY', 'FAILED', 'EXPIRED')),
    file_asset_id uuid REFERENCES file_assets(id) ON DELETE RESTRICT,
    expires_at timestamptz NOT NULL,
    generated_at timestamptz,
    failure_reason text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT export_jobs_ready_state_valid CHECK (
        (state = 'READY' AND file_asset_id IS NOT NULL AND generated_at IS NOT NULL)
        OR state <> 'READY'
    )
);

CREATE TABLE audit_events (
    id uuid PRIMARY KEY,
    inquiry_id uuid REFERENCES inquiries(id) ON DELETE RESTRICT,
    entity_type text NOT NULL,
    entity_id uuid NOT NULL,
    event_type text NOT NULL,
    actor_kind text NOT NULL CHECK (actor_kind IN ('VISITOR', 'USER', 'SYSTEM', 'INTEGRATION')),
    actor_user_id uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    occurred_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT audit_events_actor_valid CHECK (
        (actor_kind = 'USER' AND actor_user_id IS NOT NULL)
        OR (actor_kind <> 'USER' AND actor_user_id IS NULL)
    )
);

-- ============================================================================
-- Query and integrity indexes
-- ============================================================================

CREATE INDEX inquiries_route_state_submitted_idx
    ON inquiries (route, lifecycle_state, submitted_at DESC);
CREATE INDEX inquiries_qr_campaign_submitted_idx
    ON inquiries (qr_campaign_id, submitted_at DESC)
    WHERE qr_campaign_id IS NOT NULL;
CREATE INDEX inquiries_exhibition_submitted_idx
    ON inquiries (exhibition_id, submitted_at DESC)
    WHERE exhibition_id IS NOT NULL;

CREATE INDEX organizations_normalized_name_idx
    ON organizations (normalized_name);
CREATE INDEX contacts_email_normalized_idx
    ON contacts (email_normalized)
    WHERE email_normalized IS NOT NULL;
CREATE INDEX contacts_phone_e164_idx
    ON contacts (phone_e164)
    WHERE phone_e164 IS NOT NULL;
CREATE INDEX inquiry_parties_email_normalized_idx
    ON inquiry_parties (email_normalized);
CREATE INDEX inquiry_parties_phone_e164_idx
    ON inquiry_parties (phone_e164)
    WHERE phone_e164 IS NOT NULL;
CREATE INDEX inquiry_parties_company_name_idx
    ON inquiry_parties (company_name_submitted);

CREATE INDEX products_product_type_active_order_idx
    ON products (product_type_id, is_active, display_order);
CREATE INDEX products_cas_number_idx
    ON products (cas_number)
    WHERE cas_number IS NOT NULL;

CREATE INDEX supplier_inquiries_queue_idx
    ON supplier_inquiries (review_state, assigned_to_user_id, updated_at DESC);
CREATE INDEX purchase_inquiries_queue_idx
    ON purchase_inquiries (lead_state, assigned_to_user_id, updated_at DESC);
CREATE INDEX catalogue_bundles_processing_idx
    ON catalogue_bundles (processing_state, submitted_at);
CREATE INDEX purchase_line_items_inquiry_idx
    ON purchase_line_items (purchase_inquiry_id, display_order);
CREATE INDEX file_assets_inquiry_purpose_state_idx
    ON file_assets (inquiry_id, purpose, processing_state);
CREATE INDEX file_assets_bundle_idx
    ON file_assets (catalogue_bundle_id)
    WHERE catalogue_bundle_id IS NOT NULL;
CREATE INDEX location_evidence_inquiry_captured_idx
    ON location_evidence (inquiry_id, captured_at DESC);

CREATE UNIQUE INDEX review_cases_one_open_case_idx
    ON review_cases (supplier_inquiry_id)
    WHERE state IN ('OPEN', 'IN_REVIEW', 'WAITING_FOR_INFO');
CREATE INDEX review_cases_queue_idx
    ON review_cases (state, assigned_to_user_id, opened_at);
CREATE INDEX deduplication_matches_inquiry_state_idx
    ON deduplication_matches (inquiry_id, state, score DESC);
CREATE INDEX workflow_events_inquiry_time_idx
    ON workflow_events (inquiry_id, occurred_at DESC);
CREATE INDEX integration_deliveries_retry_idx
    ON integration_deliveries (state, next_attempt_at)
    WHERE state IN ('PENDING', 'RETRY_SCHEDULED');
CREATE INDEX integration_deliveries_inquiry_idx
    ON integration_deliveries (inquiry_id, created_at DESC);
CREATE INDEX export_jobs_requester_state_idx
    ON export_jobs (requested_by_user_id, state, created_at DESC);
CREATE INDEX audit_events_inquiry_time_idx
    ON audit_events (inquiry_id, occurred_at DESC)
    WHERE inquiry_id IS NOT NULL;
CREATE INDEX audit_events_entity_time_idx
    ON audit_events (entity_type, entity_id, occurred_at DESC);

-- ============================================================================
-- Updated-at triggers for mutable tables
-- ============================================================================

CREATE TRIGGER app_users_set_updated_at
BEFORE UPDATE ON app_users
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER roles_set_updated_at
BEFORE UPDATE ON roles
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER exhibitions_set_updated_at
BEFORE UPDATE ON exhibitions
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER qr_campaigns_set_updated_at
BEFORE UPDATE ON qr_campaigns
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER departments_set_updated_at
BEFORE UPDATE ON departments
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER product_types_set_updated_at
BEFORE UPDATE ON product_types
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER department_product_types_set_updated_at
BEFORE UPDATE ON department_product_types
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER pharmacopoeial_standards_set_updated_at
BEFORE UPDATE ON pharmacopoeial_standards
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER products_set_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER product_standards_set_updated_at
BEFORE UPDATE ON product_standards
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER organizations_set_updated_at
BEFORE UPDATE ON organizations
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER contacts_set_updated_at
BEFORE UPDATE ON contacts
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER inquiries_set_updated_at
BEFORE UPDATE ON inquiries
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER supplier_inquiries_set_updated_at
BEFORE UPDATE ON supplier_inquiries
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER purchase_inquiries_set_updated_at
BEFORE UPDATE ON purchase_inquiries
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER inquiry_parties_set_updated_at
BEFORE UPDATE ON inquiry_parties
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER party_addresses_set_updated_at
BEFORE UPDATE ON party_addresses
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER catalogue_bundles_set_updated_at
BEFORE UPDATE ON catalogue_bundles
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER purchase_line_items_set_updated_at
BEFORE UPDATE ON purchase_line_items
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER file_assets_set_updated_at
BEFORE UPDATE ON file_assets
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER ai_assistance_sessions_set_updated_at
BEFORE UPDATE ON ai_assistance_sessions
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER ai_extractions_set_updated_at
BEFORE UPDATE ON ai_extractions
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER ai_extracted_fields_set_updated_at
BEFORE UPDATE ON ai_extracted_fields
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER review_cases_set_updated_at
BEFORE UPDATE ON review_cases
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER integration_deliveries_set_updated_at
BEFORE UPDATE ON integration_deliveries
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

CREATE TRIGGER export_jobs_set_updated_at
BEFORE UPDATE ON export_jobs
FOR EACH ROW EXECUTE FUNCTION exhibition_portal.set_updated_at();

-- ============================================================================
-- Seed controlled standards and roles.
-- Fixed UUIDs reserve stable identifiers for initial system configuration.
-- ============================================================================

INSERT INTO roles (id, code, name, description)
VALUES
    ('00000000-0000-4000-8000-000000000001', 'ADMIN', 'Administrator', 'Full administrative access.'),
    ('00000000-0000-4000-8000-000000000002', 'SUPPLIER_REVIEWER', 'Supplier reviewer', 'Reviews and approves supplier candidates.'),
    ('00000000-0000-4000-8000-000000000003', 'MARKETING', 'Marketing user', 'Works purchase leads and records follow-up.'),
    ('00000000-0000-4000-8000-000000000004', 'EXPORTER', 'Export user', 'Creates controlled Excel exports.'),
    ('00000000-0000-4000-8000-000000000005', 'TAXONOMY_MANAGER', 'Taxonomy manager', 'Manages departments, product types, products, and standards.')
ON CONFLICT (code) DO NOTHING;

INSERT INTO pharmacopoeial_standards (id, code, name)
VALUES
    ('00000000-0000-4000-8000-000000000101', 'IP', 'Indian Pharmacopoeia'),
    ('00000000-0000-4000-8000-000000000102', 'USP', 'United States Pharmacopeia'),
    ('00000000-0000-4000-8000-000000000103', 'BP', 'British Pharmacopoeia'),
    ('00000000-0000-4000-8000-000000000104', 'EP', 'European Pharmacopoeia')
ON CONFLICT (code) DO NOTHING;

COMMENT ON SCHEMA exhibition_portal IS
    'Database objects for the Sarv Biolabs exhibition and reusable inquiry portal.';
COMMENT ON TABLE inquiries IS
    'The portal source of truth for a visitor submission. A route extension records supplier or purchase-specific workflow.';
COMMENT ON TABLE inquiry_parties IS
    'Original visitor-submitted person/company snapshot; canonical contact and organization links are optional.';
COMMENT ON TABLE file_assets IS
    'Metadata-only registry for objects held in secure storage. File bytes are never persisted in PostgreSQL.';
COMMENT ON TABLE location_evidence IS
    'Voluntary consent-backed evidence. Exact coordinates are encrypted and scheduled for purge; raw IP addresses are not stored.';
COMMENT ON TABLE ai_extracted_fields IS
    'Reviewable AI suggestions. Acceptance or correction is required before any value becomes user-confirmed data.';
COMMENT ON TABLE integration_deliveries IS
    'Idempotent outbound delivery outbox and retry record for vendor and marketing destinations.';

COMMIT;
