export const copy = {
  appName: 'Sarv Biolabs Exhibition Portal',
  prototypeBanner:
    'Development: drafts save to the Java API when connected. Shared stall tablets keep only a session pointer — not contact details — in the browser.',
  connectionLost:
    'Connection lost. Typed answers stay on this screen until you reconnect. Submit needs the API for a receipt reference.',
  staffAssistBanner:
    'Staff-assisted capture. When this visitor is finished, tap Next visitor to clear the session.',
  sharedDeviceHint: 'Shared device — tap Next visitor after each person.',
  cardCapture: {
    title: 'Start with your business card',
    subtitle:
      'Capture both sides if you have a card, or continue without one. If a QR on the card encodes contact details, we suggest them for you to check next — nothing is submitted until you confirm.',
    frontLabel: 'Front side',
    backLabel: 'Back side',
    useCamera: 'Use camera',
    upload: 'Upload',
    takePhoto: 'Take photo',
    removePhoto: 'Remove photo',
    retakePhoto: 'Retake',
    continueWithout: 'Continue without a card',
    backLocked: 'Complete front side first',
    qrNote:
      'If a QR code is present on your card, it is stored with your inquiry for internal use only. This app does not open or preview QR destinations.',
    cameraUnavailable: 'Camera is not available here. Use upload or continue without a card.',
    insecureContextNote:
      'This page is not HTTPS, so the in-page camera is unavailable. Upload a photo, use the phone file picker, or continue without a card.',
    processing: 'Preparing photo…',
    processingFailed:
      'Could not load that photo — it may be too large for this browser. Try again or use a smaller image.',
    consentTitle: 'Store card images with this inquiry',
    consentBody:
      'Images are kept privately with this draft so the stall team can follow up. They are not published. With your agreement we may suggest contact fields from a card QR for you to review. You can continue without a card.',
    consentGrant: 'I agree to store card images with this inquiry',
    consentRequired: 'Agree to store the card, or continue without a card.',
    cameraPermissionTitle: 'Camera access',
    cameraPermissionBody:
      'Your phone will ask for camera permission next. The photo is stored with this inquiry only. It is not posted publicly.',
    cameraPermissionContinue: 'Allow camera',
    uploading: 'Uploading…',
  },
  contact: {
    title: 'Check your contact details',
    subtitle:
      'Confirm your name, work email, and mobile number. We’ll save your progress as you continue.',
    fromCard: 'From card upload',
    fromSuggestions: 'Suggested from your card — please check and edit if needed',
    savedNote:
      'Your draft is saved as you continue. You can return later and we’ll keep what you’ve entered.',
    retake: 'Retake card photos',
    continue: 'Continue to choose your path',
  },
  intent: {
    saved: 'Your details are saved.',
    changeContact: 'Change contact details',
    title: 'What would you like to do?',
    subtitle: 'Choose the path that fits your visit today.',
    sellTitle: 'I want to sell',
    sellDesc: 'Tell Sarv about the products or capabilities you can supply.',
    buyTitle: 'I want to buy',
    buyDesc: 'Start a quick product inquiry. Add only the details you know.',
    footer: '© 2026 Sarv Biolabs. Mineral Research Precision.',
    policyUnavailable: 'Not available in this release',
  },
  supplier: {
    intake: 'Supplier intake',
    departmentsTitle: 'Which departments do you want to work with?',
    departmentsSubtitle: 'Select one or more areas. We’ll show relevant product types next.',
    departmentsNote: 'The available departments are configured for this exhibition.',
    productTypesTitle: 'Which product types can you supply?',
    productTypesSubtitle: 'Filtered by your selected departments.',
    smartDetailsTitle: 'Check your supplier details',
    smartDetailsSubtitle: 'Review what we have and add only what’s missing.',
    fromCard: 'From your business card',
    onlyMissing: 'Only if something is missing',
    allFound: 'All required details found',
    optionalCompany: 'Add optional company details',
    optionalCompanyHint: 'You can skip this — our team can follow up.',
    reviewTitle: 'Review request',
    reviewSubtitle: 'Review details below before final submission.',
    companyContacts: 'Company & contacts',
    supplyCapability: 'Supply capability',
    supportingInfo: 'Supporting information',
    catalogue: 'Catalogue',
    catalogueHint: 'PDF or JPEG/PNG/WebP, stored privately with this inquiry',
    website: 'Website URL',
    websiteHint: 'Company or product page',
    websiteOrCatalogue: 'Add a catalogue or website — at least one is required. You can add both.',
    reviewQueueNote: 'Request will enter internal review queue.',
    submit: 'Submit supplier request',
    confirmationTitle: 'Supplier request received',
    confirmationBody:
      'Thank you. Your supplier request has been recorded for internal review. Our team will assess your details and follow up if needed. This is not an approval or vendor onboarding confirmation.',
    savedSelections: 'Your selections and details are saved.',
    continueReview: 'Continue to review',
  },
  buyer: {
    needTitle: 'What are you looking for?',
    needSubtitle: 'Tell us the product or requirement. You can add details only if you know them.',
    contactSaved: 'Your contact details are saved',
    requirementLabel: 'Product or requirement',
    requirementHint: 'A short description is enough to start.',
    searchAreas: 'Search our product areas (optional)',
    exactProduct: 'I know the exact product',
    specsTitle: 'Add specifications (optional)',
    specsHint: 'Quantity, pack size, standard, needed-by date, or notes.',
    teamFollowUp: 'Our team can follow up for anything else.',
    autoSave: 'Changes save automatically',
    review: 'Review my inquiry',
    reviewTitle: 'Review your inquiry',
    reviewSubtitle: 'Everything looks ready to send.',
    whatYouNeed: 'What you need',
    specifications: 'Specifications',
    noSpecs: 'No extra specifications added',
    contactDetails: 'Contact details',
    savedFromCard: 'Saved from card',
    editContact: 'Edit contact details',
    followUpNote: 'Our team may contact you for any details we still need.',
    savedUntilSubmit: 'Your inquiry is saved until you submit.',
    submit: 'Submit inquiry',
    confirmationTitle: 'Inquiry received',
    confirmationBody:
      'Thank you. Your product inquiry has been recorded. Our sales or marketing team will review it and contact you if more detail is needed. We have not assumed availability, standards, or response times.',
  },
  common: {
    continue: 'Continue',
    back: 'Go back',
    edit: 'Edit',
    restart: 'Restart demo',
    nextVisitor: 'Next visitor',
    restartConfirm: 'Clear this session and start over for the next visitor?',
    receiptReference: 'Receipt reference',
    stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
    savedAutomatically: 'Saved automatically',
    search: 'Search',
    localFileOnly: 'Selected on this device only — API is offline',
    uploaded: 'Stored with this inquiry',
  },
} as const
